name: step_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  pedometer: 4.0.1
  sqflite: ^2.0.0+4
  http: ^0.13.3
  path: ^1.8.0
  fl_chart: ^0.30.0
  animations: ^2.0.1
  flutter_local_notifications: ^9.0.0
  lottie: ^1.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_animation.json
    - assets/walk_animation.json
    - assets/car1.png
    - assets/car2.png
    - assets/car3.png
    - assets/car4.png
    - assets/car5.png
    - assets/car6.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
