// lib/journey_data.dart

final List<Map<String, String>> journeys = [
  {
    'image': 'assets/car1.png',
    'name': 'Toyota Corolla',
    'plate': '34 ABC 123',
    'route': 'İstanbul - Ankara',
    'date': '01.07.2024 - 18:00',
    'rating': '4.5',
    'capacity': '4',
  },
  {
    'image': 'assets/car2.png',
    'name': 'Honda Civic',
    'plate': '34 DEF 456',
    'route': 'Ankara - İzmir',
    'date': '02.07.2024 - 18:00',
    'rating': '4.7',
    'capacity': '5',
  },
  {
    'image': 'assets/car3.png',
    'name': 'Ford Focus',
    'plate': '34 GHI 789',
    'route': 'İzmir - Antalya',
    'date': '03.07.2024 - 18:00',
    'rating': '4.3',
    'capacity': '4',
  },
  {
    'image': 'assets/car4.png',
    'name': 'BMW 3 Series',
    'plate': '34 JKL 012',
    'route': 'Antalya - Bursa',
    'date': '04.07.2024 - 18:00',
    'rating': '4.8',
    'capacity': '5',
  },
  {
    'image': 'assets/car5.png',
    'name': 'Mercedes-Benz C-Class',
    'plate': '34 MNO 345',
    'route': 'Bursa - Eskişehir',
    'date': '05.07.2024 - 18:00',
    'rating': '4.6',
    'capacity': '4',
  },
  {
    'image': 'assets/car6.png',
    'name': 'Audi A4',
    'plate': '34 PQR 678',
    'route': 'Eskişehir - Konya',
    'date': '06.07.2024 - 18:00',
    'rating': '4.9',
    'capacity': '5',
  },
];
